### ISSUE TITLE
typo error on "t-tests_in_practice.html"

### ISSUE THREAD

**Issue by t0mst0ne** [genomicsclass/book#1]
http://genomicsclass.github.io/book/pages/t-tests_in_practice.html

A problem is that we do not know the population standard deviation. So we use the sample standard deviation as an estimate. In R we simply use the sd function and the SE is simply

sd(control)/length(control)
## [1] 0.2518784

Should be :
sd(control)/sqrt(length(control))

**Comment by mikelove** [comment]
thanks. you're right. you can also fix these directly by issuing pull requests here:

https://github.com/genomicsclass/labs
